#!/usr/bin/env php
<?php
require 'vendor/autoload.php';

use Acme\NewCommand;
use GuzzleHttp\Client;
use Symfony\Component\Console\Application;

$app = new Application('laracast', '1.0');
$app->add(new NewCommand(new Client));
$app->run();
